### ISSUE TITLE
How username, roles and token will be fetched from NGINX.

### ISSUE THREAD

**Issue by dhirendraps** [IHTSDO/authoring-services#1]
If we are not overriding the value of the given fields in application.properties file, how these values are populating in WebSecurityConfig class from NGINX

      ims-security.required-role

     authentication.override.username
     authentication.override.roles
     authentication.override.token

And what entities are important for making calls to the REST resources in authoring-services.

**Comment by kaicode** [comment]
When a request is made to Authoring Services, Nginx takes the single sign-on cookie from HTTP request and accesses the Identity Management Service to authenticate the security token in the cookie and to lookup the username and roles. These are included in the forwarded request to Authoring Services in the X-AUTH headers.

In Authoring Services in the `WebSecurityConfig` the filter `RequestHeaderAuthenticationDecorator` is added to the `HttpSecurity` builder. This filter takes the username, roles and token values from the "X-AUTH.." HTTP headers provided by Nginx.

In our setup the REST resources within Authoring Services which access other connected resources need some of the security entities.

In our setup Snow Owl is behind an Nginx proxy which requires the single sign-on cookie The Snow Owl client used in Authoring Services takes the `SecurityUtil.getAuthenticationToken()` which is the single sign-on cookie and includes it in the HTTP headers of each request made to Snow Owl.

The security username in Authoring Services is used in the JIRA client factory to create a Jira client which accesses Jira as that user. This is useful because it means that user actions on a task ticket are logged in Jira under that username. It also let's us control the visibility of authoring projects using Jira user permissions.

I hope this answers your question.
