### ISSUE TITLE
Is Jira mandatory ?

### ISSUE THREAD

**Issue by Myu-Unix** [IHTSDO/authoring-services#8]
Hello dears,

can the Jira connection be bypassed or is it mandatory to run the authoring-services ?

Kind regards

**Comment by kaicode** [comment]
Hey. Right now the Jira connection is mandatory. The initial plan was to use Jira just as workflow state engine for authoring tasks but it grew into more than that. We also use a special Jira ticket for authoring projects which holds some custom fields as a convenient way to enable and disable some features within the authoring platform on a per-project basis.

I would love to see some sort of abstract layer here so that an alternative (preferably open source) workflow engine could be plugged in instead of Jira but as the Jira licence for the first 10 users is only 10 USD this work has never been started.

If you would like to set up a Jira server here is a config dump to set up authoring projects with the correct workflow and custom fields. One ticket of type "SCA Authoring Project" is required for each authoring project, then the tasks will be of ticket type "SCA Authoring Task" which are created by authoring-services.
[config-dump_SNOWSTORM_TEST_JIRA_.zip](https://github.com/IHTSDO/authoring-services/files/5164695/config-dump_SNOWSTORM_TEST_JIRA_.zip)

Kind regards,
Kai
